version: '3'

services:
  app:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
  db:
    image: mysql:8.0.27
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
